// automatically generated by the FlatBuffers compiler, do not modify

package org.luckypray.dexkit.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
internal class `-InstructionMeta` : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : `-InstructionMeta` {
        __init(_i, _bb)
        return this
    }
    val index : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    fun mutateIndex(index: UInt) : Boolean {
        val o = __offset(4)
        return if (o != 0) {
            bb.putInt(o + bb_pos, index.toInt())
            true
        } else {
            false
        }
    }
    val opcode : Int
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    fun mutateOpcode(opcode: Int) : Boolean {
        val o = __offset(6)
        return if (o != 0) {
            bb.putInt(o + bb_pos, opcode)
            true
        } else {
            false
        }
    }
    val operandType : Byte
        get() {
            val o = __offset(8)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    fun mutateOperandType(operandType: Byte) : Boolean {
        val o = __offset(8)
        return if (o != 0) {
            bb.put(o + bb_pos, operandType)
            true
        } else {
            false
        }
    }
    val methodRef : `-MethodMeta`? get() = methodRef(`-MethodMeta`())
    fun methodRef(obj: `-MethodMeta`) : `-MethodMeta`? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val fieldRef : `-FieldMeta`? get() = fieldRef(`-FieldMeta`())
    fun fieldRef(obj: `-FieldMeta`) : `-FieldMeta`? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val classRef : `-ClassMeta`? get() = classRef(`-ClassMeta`())
    fun classRef(obj: `-ClassMeta`) : `-ClassMeta`? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val stringValue : String?
        get() {
            val o = __offset(16)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val stringValueAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(16, 1)
    fun stringValueInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 16, 1)
    val literalValue : Long
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    fun mutateLiteralValue(literalValue: Long) : Boolean {
        val o = __offset(18)
        return if (o != 0) {
            bb.putLong(o + bb_pos, literalValue)
            true
        } else {
            false
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_23_5_26()
        fun getRootAsInstructionMeta(_bb: ByteBuffer): `-InstructionMeta` = getRootAsInstructionMeta(_bb, `-InstructionMeta`())
        fun getRootAsInstructionMeta(_bb: ByteBuffer, obj: `-InstructionMeta`): `-InstructionMeta` {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createInstructionMeta(builder: FlatBufferBuilder, index: UInt, opcode: Int, operandType: Byte, methodRefOffset: Int, fieldRefOffset: Int, classRefOffset: Int, stringValueOffset: Int, literalValue: Long) : Int {
            builder.startTable(8)
            addLiteralValue(builder, literalValue)
            addStringValue(builder, stringValueOffset)
            addClassRef(builder, classRefOffset)
            addFieldRef(builder, fieldRefOffset)
            addMethodRef(builder, methodRefOffset)
            addOpcode(builder, opcode)
            addIndex(builder, index)
            addOperandType(builder, operandType)
            return endInstructionMeta(builder)
        }
        fun startInstructionMeta(builder: FlatBufferBuilder) = builder.startTable(8)
        fun addIndex(builder: FlatBufferBuilder, index: UInt) = builder.addInt(0, index.toInt(), 0)
        fun addOpcode(builder: FlatBufferBuilder, opcode: Int) = builder.addInt(1, opcode, 0)
        fun addOperandType(builder: FlatBufferBuilder, operandType: Byte) = builder.addByte(2, operandType, 0)
        fun addMethodRef(builder: FlatBufferBuilder, methodRef: Int) = builder.addOffset(3, methodRef, 0)
        fun addFieldRef(builder: FlatBufferBuilder, fieldRef: Int) = builder.addOffset(4, fieldRef, 0)
        fun addClassRef(builder: FlatBufferBuilder, classRef: Int) = builder.addOffset(5, classRef, 0)
        fun addStringValue(builder: FlatBufferBuilder, stringValue: Int) = builder.addOffset(6, stringValue, 0)
        fun addLiteralValue(builder: FlatBufferBuilder, literalValue: Long) = builder.addLong(7, literalValue, 0L)
        fun endInstructionMeta(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}