// automatically generated by the FlatBuffers compiler, do not modify

package org.luckypray.dexkit.schema

@Suppress("unused")
internal class `-OperandType` private constructor() {
    companion object {
        const val None: Byte = 0
        const val MethodRef: Byte = 1
        const val FieldRef: Byte = 2
        const val ClassRef: Byte = 3
        const val String: Byte = 4
        const val Literal: Byte = 5
    }
}